name: Build Next.js app

on:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upgrade mantine packages
        run: |
          npm run update-package
          npm install

      - name: Commit updated files
        run: |
          git config core.filemode false
          if ! git diff --exit-code --quiet
          then
            git add -A
            git config user.name thr3a
            git config user.email thr3a@example.com
            git commit -m "update: update package"
            git push
          fi
  build:
    needs: update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout official repository
        run: |
          git clone --depth 1 https://github.com/mantinedev/mantine.git /tmp/mantine
          bash setup.sh

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install NPM packages
        run: npm ci

      - name: Generate document and code
        run: node --loader ts-node/esm scripts/generateData.ts

      - name: Build Next.js app
        run: npm run build

      - name: Export Next.js app
        run: npm run export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
          # cname: turai.work

      - name: Notification discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
